name: Python Application CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Verify Python installation
      run: |
        python3 --version  # Check Python version
        which python3  # Check Python path

    - name: Install virtualenv
      run: |
        pip install virtualenv  # Install virtualenv globally

    - name: Create virtual environment with virtualenv
      run: |
        virtualenv venv  # Use virtualenv to create the virtual environment
        ls -la venv/bin  # Check if the venv directory is created and contains necessary files

    - name: Install dependencies
      run: |
        . venv/bin/activate  # Activate the virtual environment
        pip install --upgrade pip  # Upgrade pip
        pip install -r requirements.txt  # Install dependencies

    - name: Run the application
      run: |
        . venv/bin/activate  # Activate the virtual environment again
        make run &  # Run the app and wait for a few seconds
        sleep 10  # Wait for the server to start up
        kill $!  # Stop the server after the test
