name: Python Application CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python3 -m venv venv 
        . venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run the application
      run: |
        . venv/bin/activate
        make run &
        sleep 10
        kill $!
